apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - uvicorn
            - app.main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev"
            - name: CAST_SERVICE_HOST_URL
              value: "http://cast-service:8000/api/v1/casts/"
            - name: POSTGRES_USER
              value: "movie_db_username"
            - name: POSTGRES_PASSWORD
              value: "movie_db_password"
            - name: POSTGRES_DB
              value: "movie_db_dev"
          volumeMounts:
            - name: movie-service-volume
              mountPath: /app
      volumes:
        - name: movie-service-volume
          hostPath:
            path: /home/ubuntu/jenkins_devops_exams/movie-service
            type: Directory
