apiVersion: v1
    kind: Service
    metadata:
      name: movie-service
    spec:
      ports:
        - protocol: TCP
          port: 8001
          targetPort: 8000
      selector:
        app: movie-service
