apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - uvicorn
            - app.main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev"
            - name: POSTGRES_USER
              value: "cast_db_username"
            - name: POSTGRES_PASSWORD
              value: "cast_db_password"
            - name: POSTGRES_DB
              value: "cast_db_dev"
          volumeMounts:
            - name: cast-service-volume
              mountPath: /app
      volumes:
        - name: cast-service-volume
          hostPath:
            path: /home/ubuntu/jenkins_devops_exams/cast-service
            type: Directory
