apiVersion: v1
    kind: Service
    metadata:
      name: cast-service
    spec:
      ports:
        - protocol: TCP
          port: 8002
          targetPort: 8000
      selector:
        app: cast-service
