apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 8080;
      location / {
        proxy_pass http://movie-service:8001;
      }
    }
